name: deploy-service-cloud-run

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "app.py"
      - "py_processing/**"
      - "requirements.txt"
      - "Dockerfile"
      - "terraform/deploy/**"
      - ".github/workflows/deploy-service.yml"

  workflow_dispatch:
    inputs:
      endpoint:
        description: "Prueba que se quiere ejecutar"
        required: true
        default: "ambos"
        type: choice
        options:
          - logo
          - texto
          - ambos

      solo_test:
        description: "Ejecutar solamente las pruebas Python"
        required: true
        default: true
        type: boolean

      logo_payload:
        description: "JSON para /agregar_logo_a_imagen"
        required: true
        default: |
          {
            "base_path": "camping.jpg",
            "scale": 0.30,
            "opacity": 0.80,
            "margin": 0.02,
            "tolerance": 60,
            "bg_color": null,
            "position": "right"
          }
        type: string

      texto_payload:
        description: "JSON para /poner_texto_a_imagen"
        required: true
        default: |
          {
            "image_path": "camping.jpg",
            "text": "Foto de la NASA",
            "fontsize": 0.03,
            "color": "skyblue",
            "position": ["center", "top"],
            "margin": 0.05,
            "max_width_pct": 0.92,
            "font_path": "CrayonLibre-Regular.ttf"
          }
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  test-app-python:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_ARTIFACT_REGISTRY_REPO: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPO }}
      GCP_TERRAFORM_STATE_BUCKET: ${{ secrets.GCP_TERRAFORM_STATE_BUCKET }}
      GCP_BUCKET_VOLUME: ${{ secrets.GCP_BUCKET_VOLUME }}

      TEST_MODE: ${{ inputs.endpoint || 'ambos' }}

      LOGO_PAYLOAD: ${{ inputs.logo_payload || '{"base_path":"camping.jpg","scale":0.30,"opacity":0.80,"margin":0.02,"tolerance":60,"bg_color":null,"position":"right"}' }}

      TEXT_PAYLOAD: ${{ inputs.texto_payload || '{"image_path":"camping.jpg","text":"Foto de la NASA","fontsize":0.03,"color":"skyblue","position":["center","top"],"margin":0.05,"max_width_pct":0.92}' }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # para intentar ocultar info de cualquier log de salida
      - name: Mask GCP identifiers
        run: |
          echo "::add-mask::$GCP_PROJECT_ID"
          echo "::add-mask::$GCP_PROJECT_NUMBER"
          echo "::add-mask::$GCP_SERVICE_ACCOUNT"
          echo "::add-mask::$GCP_WIF_PROVIDER"
          echo "::add-mask::$GCP_REGION"
          echo "::add-mask::$GCP_ARTIFACT_REGISTRY_REPO"
          echo "::add-mask::$GCP_TERRAFORM_STATE_BUCKET"
          echo "::add-mask::$GCP_BUCKET_VOLUME"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare test folders
        run: |
          mkdir -p imagenes_base
          mkdir -p salida_procesos
        #rm -f salida_procesos/*  toca verificar bien el test que no se interfieran entre las pruebas

      - name: Validate JSON payloads
        run: |
          echo "$LOGO_PAYLOAD" | jq empty
          echo "$TEXT_PAYLOAD" | jq empty

          echo "JSON de logo válido"
          echo "JSON de texto válido"

      - name: Determine test image
        run: |
          if [ "$TEST_MODE" = "texto" ]; then
            TEST_IMAGE=$(echo "$TEXT_PAYLOAD" | jq -r '.image_path')
          else
            TEST_IMAGE=$(echo "$LOGO_PAYLOAD" | jq -r '.base_path')
          fi

          if [ -z "$TEST_IMAGE" ] || [ "$TEST_IMAGE" = "null" ]; then
            echo "No se encontró la ruta de la imagen de prueba."
            exit 1
          fi

          echo "Imagen de prueba: $TEST_IMAGE"

          echo "TEST_IMAGE=$TEST_IMAGE" >> "$GITHUB_ENV"

      - name: Download test image
        run: |
          local_image="${TEST_IMAGE//\//___}"

          gcloud storage cp \
            "gs://$GCP_BUCKET_VOLUME/volume-cloud-run/$TEST_IMAGE" \
            "$GITHUB_WORKSPACE/$local_image"

          echo "LOCAL_IMAGE=$local_image" >> "$GITHUB_ENV"

      - name: Download logo
        if: env.TEST_MODE == 'logo' || env.TEST_MODE == 'ambos'
        run: |
          gcloud storage cp \
            "gs://$GCP_BUCKET_VOLUME/volume-cloud-run/imagenes_base/prueba_logotipo.png" \
            "$GITHUB_WORKSPACE/imagenes_base/prueba_logotipo.png"

      # la app debe quedar corriendo en segundo plano
      - name: Start Flask app
        run: |
          python app.py > app.log 2>&1 &
          sleep 5

      - name: Run logo test
        if: env.TEST_MODE == 'logo' || env.TEST_MODE == 'ambos'
        run: |

          logo_payload=$(echo "$LOGO_PAYLOAD" | jq \
            --arg image "$LOCAL_IMAGE" \
            '.base_path = $image')

          echo "Ejecutando /agregar_logo_a_imagen"

          curl --fail --show-error --request POST \
            --header "Content-Type: application/json" \
            --data "$logo_payload" \
            http://localhost:8080/agregar_logo_a_imagen

          filename=$(basename "$LOCAL_IMAGE")
          filename_without_extension="${filename%.*}"

          LOGO_OUTPUT="${filename_without_extension}_con_logo.png"

          test -f "$GITHUB_WORKSPACE/salida_procesos/$LOGO_OUTPUT"
          echo "Prueba de logo exitosa"

          echo "Salida del logo:"
          echo "$LOGO_OUTPUT"

          echo "LOGO_OUTPUT=$LOGO_OUTPUT" >> "$GITHUB_ENV"

      - name: Run text test
        if: env.TEST_MODE == 'texto' || env.TEST_MODE == 'ambos'
        run: |

          if [ "$TEST_MODE" = "ambos" ]; then

            # La salida del logo está dentro de salida_procesos.
            # Por eso esta es la ruta que debe recibir app.py.
            TEXT_INPUT="salida_procesos/$LOGO_OUTPUT"

          else

            # Para texto solamente se utiliza la imagen descargada.
            TEXT_INPUT="$LOCAL_IMAGE"

          fi

          text_payload=$(echo "$TEXT_PAYLOAD" | jq \
            --arg image "$TEXT_INPUT" \
            '.image_path = $image')

          echo "Ejecutando /poner_texto_a_imagen"
          echo "Imagen de entrada del texto: $TEXT_INPUT"

          curl --fail --show-error --request POST \
            --header "Content-Type: application/json" \
            --data "$text_payload" \
            http://localhost:8080/poner_texto_a_imagen

          text_filename=$(basename "$TEXT_INPUT")
          text_filename_without_extension="${text_filename%.*}"

          TEXT_OUTPUT="${text_filename_without_extension}_con_texto.png"

          test -f "$GITHUB_WORKSPACE/salida_procesos/$LOGO_OUTPUT"
          echo "Prueba de texto exitosa"

          echo "Salida del texto:"
          echo "$TEXT_OUTPUT"

          echo "TEXT_OUTPUT=$TEXT_OUTPUT" >> "$GITHUB_ENV"

      - name: Upload logo output to GCS
        if: env.TEST_MODE == 'logo'
        run: |
          gcloud storage cp \
            "$GITHUB_WORKSPACE/salida_procesos/$LOGO_OUTPUT" \
            "gs://$GCP_BUCKET_VOLUME/volume-cloud-run/salida_procesos_github_actions/$LOGO_OUTPUT"

          echo "Archivo subido:"
          echo "gs://$GCP_BUCKET_VOLUME/volume-cloud-run/salida_procesos_github_actions/$LOGO_OUTPUT"

      - name: Upload output to GCS
        run: |
          if [ "$TEST_MODE" = "logo" ]; then
          output="$LOGO_OUTPUT"
          else
            output="$TEXT_OUTPUT"
          fi

          gcloud storage cp \
            "$GITHUB_WORKSPACE/salida_procesos/$output" \
            "gs://$GCP_BUCKET_VOLUME/volume-cloud-run/salida_procesos_github_actions/$output"

          echo "Archivo subido:"
          echo "gs://$GCP_BUCKET_VOLUME/volume-cloud-run/salida_procesos_github_actions/$output"

      - name: Show app log
        if: always()
        run: |
          cat app.log
          
  docker_test:
    needs: test-app-python
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.solo_test == false

    #para que quede pausado esperando aprobacion y poder primero ver si la prueba de codigo python quedo bien
    environment: gcp-infrastructure 

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_ARTIFACT_REGISTRY_REPO: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPO }}
      GCP_TERRAFORM_STATE_BUCKET: ${{ secrets.GCP_TERRAFORM_STATE_BUCKET }}
      GCP_BUCKET_VOLUME: ${{ secrets.GCP_BUCKET_VOLUME }}

      TEST_IMAGE: ${{ inputs.base_img || 'camping.jpg' }}
      TEST_SCALE: ${{ fromJSON(format('{0}', inputs.scale) || '0.3') }}
      TEST_OPACITY: ${{ fromJSON(format('{0}', inputs.opacity) || '0.8') }}
      TEST_MARGIN: ${{ fromJSON(format('{0}', inputs.margin) || '0.02') }}
      TEST_TOLERANCE: ${{ fromJSON(format('{0}', inputs.tolerance) || '60') }}
      TEST_POSITION: ${{ inputs.position || 'right' }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # para intentar ocultar info de cualquier log de salida
      - name: Mask GCP identifiers
        run: |
          echo "::add-mask::$GCP_PROJECT_ID"
          echo "::add-mask::$GCP_PROJECT_NUMBER"
          echo "::add-mask::$GCP_SERVICE_ACCOUNT"
          echo "::add-mask::$GCP_WIF_PROVIDER"
          echo "::add-mask::$GCP_REGION"
          echo "::add-mask::$GCP_ARTIFACT_REGISTRY_REPO"
          echo "::add-mask::$GCP_TERRAFORM_STATE_BUCKET"
          echo "::add-mask::$GCP_BUCKET_VOLUME"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Prepare test folders
        run: |
          mkdir -p imagenes_base
          mkdir -p salida_procesos

      - name: Download test image
        run: |
          local_image="${TEST_IMAGE//\//___}"

          gcloud storage cp \
            "gs://$GCP_BUCKET_VOLUME/volume-cloud-run/$TEST_IMAGE" \
            "$GITHUB_WORKSPACE/$local_image"

      - name: Download logo
        run: |
          gcloud storage cp \
            "gs://$GCP_BUCKET_VOLUME/volume-cloud-run/imagenes_base/prueba_logotipo.png" \
            "$GITHUB_WORKSPACE/imagenes_base/prueba_logotipo.png"

      - name: Build Docker image
        run: |
          docker build \
            -t astro-image-processing:test \
            .

      - name: Start Docker container
        run: |
          docker run \
          -d \
          --name astro-image-processing-test \
          -p 8080:8080 \
          -e K_SERVICE=astro-image-processing \
          -v "$GITHUB_WORKSPACE:/mnt/bucket" \
          astro-image-processing:test

          sleep 5

      - name: Run Docker image processing test
        run: |
          local_image="${TEST_IMAGE//\//___}"

          curl --fail --show-error --request POST \
            --header "Content-Type: application/json" \
            --data '{
              "base_path": "'"$local_image"'",
              "scale": '"$TEST_SCALE"',
              "opacity": '"$TEST_OPACITY"',
              "margin": '"$TEST_MARGIN"',
              "tolerance": '"$TEST_TOLERANCE"',
              "bg_color": null,
              "position": "'"$TEST_POSITION"'"
            }' \
            http://localhost:8080/agregar_logo_a_imagen

      - name: Verify Docker output
        run: |
          local_image="${TEST_IMAGE//\//___}"
          filename=$(basename "$local_image")
          filename_without_extension="${filename%.*}"

          output="$GITHUB_WORKSPACE/salida_procesos/${filename_without_extension}_con_logo.png"

          test -f "$output"

          echo "Prueba Docker exitosa"
          echo "Archivo generado: $output"

      - name: Push Docker image to Artifact Registry
        run: |
          gcloud auth configure-docker "$GCP_REGION-docker.pkg.dev" --quiet

          docker tag \
            astro-image-processing:test \
            "$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REGISTRY_REPO/astro-image-processing:${GITHUB_SHA}"

          docker push \
            "$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REGISTRY_REPO/astro-image-processing:${GITHUB_SHA}"

      - name: Show Docker logs
        if: always()
        run: |
          docker logs astro-image-processing-test

  deploy_cloud_run:
    needs: docker_test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.solo_test == false

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_ARTIFACT_REGISTRY_REPO: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPO }}
      GCP_TERRAFORM_STATE_BUCKET: ${{ secrets.GCP_TERRAFORM_STATE_BUCKET }}
      GCP_BUCKET_VOLUME: ${{ secrets.GCP_BUCKET_VOLUME }}

      DOCKER_IMAGE: "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY_REPO }}/astro-image-processing:${{ github.sha }}"

    defaults:
      run:
        working-directory: terraform/deploy

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Mask GCP identifiers
        run: |
          echo "::add-mask::$GCP_PROJECT_ID"
          echo "::add-mask::$GCP_PROJECT_NUMBER"
          echo "::add-mask::$GCP_SERVICE_ACCOUNT"
          echo "::add-mask::$GCP_WIF_PROVIDER"
          echo "::add-mask::$GCP_REGION"
          echo "::add-mask::$GCP_ARTIFACT_REGISTRY_REPO"
          echo "::add-mask::$GCP_TERRAFORM_STATE_BUCKET"
          echo "::add-mask::$GCP_BUCKET_VOLUME"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=$GCP_TERRAFORM_STATE_BUCKET"

      - name: Terraform Apply
        run: |
          terraform apply \
            -auto-approve
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.GCP_REGION }}
          TF_VAR_docker_image: ${{ env.DOCKER_IMAGE }}
          TF_VAR_gcs_bucket: ${{ secrets.GCP_BUCKET_VOLUME }}